import React from 'react'

function MonCopropriete() {
  return (
    <div>MonCopropriete
        <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Iure tenetur similique autem consequuntur dolorem nesciunt ipsam laborum ut et ipsum qui itaque eligendi, officiis omnis placeat iste consequatur quisquam quibusdam incidunt earum! Numquam unde minus eum, repellendus obcaecati quidem ducimus dignissimos accusantium. Iusto debitis enim fuga sequi odit harum ad aspernatur. Iure itaque quas est nihil, ducimus numquam voluptatibus soluta earum iusto esse quos deleniti, error dolorem cupiditate amet blanditiis illum rem, temporibus dolores hic autem obcaecati exercitationem ratione iste. Tempore quidem accusantium dolor unde quos id veniam. Similique perspiciatis cupiditate, officia eos tempore natus necessitatibus laudantium corporis incidunt animi, quasi earum accusamus iste ratione ad. Nulla minus, hic praesentium iste facilis quod. Atque perspiciatis veritatis distinctio aliquid eaque vel quos laudantium aspernatur magnam corporis facilis esse dolorem, quod quidem, quas nemo facere impedit? Quae, recusandae. Perspiciatis minima quia, officiis ex illum modi error ullam harum architecto aliquid cum, tempore expedita est explicabo dolorum qui quidem eveniet? Tempora sint, numquam voluptatibus, id, facilis quas quod eaque porro sequi neque non! Reprehenderit voluptatem facere nemo cum voluptates temporibus accusamus doloremque, provident itaque porro labore voluptatum, totam quisquam, quaerat aliquid assumenda ut. Fugiat in tempore nesciunt corrupti corporis explicabo? Minima, placeat praesentium. Illum ipsam molestiae modi, deleniti, laboriosam facere expedita fugit unde consectetur dolores placeat odio. Placeat quas temporibus eum in sed vero consequatur, nam repellat voluptates. Minima animi natus, recusandae autem qui, eius reprehenderit, cupiditate a repellendus esse cumque! Natus incidunt velit officia quam exercitationem autem, dolores beatae quasi, aut quae, illo sapiente inventore ad facilis rerum nisi? Officia sapiente laboriosam eum maxime quidem? Officia nostrum porro provident eveniet soluta iste ad est quibusdam. Doloremque molestiae aliquid doloribus inventore, quae expedita. Ullam enim veniam omnis unde iusto totam laboriosam natus nihil aut repudiandae, dolore facilis ipsum possimus harum excepturi illum nisi?</p>
    </div>
  )
}

export default MonCopropriete